version: 2.1
orbs:
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
  node: circleci/node@4.7.0
workflows:
  elastic-beanstalk-workflow:
    jobs:
      - node/test:
          app-dir: ~/project/backend
      - aws-elastic-beanstalk/deploy:
          app-dir: ~/project/backend
          context: aws-creds
          application-name: SDSU deployment practice
          environment-name: SDSUdeploymentpractice-env

          filters:
            branches:
              only:
                - main
          label: version-<<pipeline.number>>
          requires:
            - node/test

         

